
import type { Metadata } from "next";
import "../app/styles/styles.css"
import Header from "./components/layout/Header/Header";
import { Jost } from 'next/font/google'
import Footer from "./components/layout/Footer/Footer";
import CartContext from "./context/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jost = Jost({
  adjustFontFallback:true,
  subsets:["latin"]
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {
  return (
    <html lang="it">
      <body className={`app ${jost.className}`}>
        <Header/>
        <main>
          <CartContext>
            {children}
          </CartContext>
        </main>
        <Footer/>
      </body>
    </html>
  );
}
