import type { Metadata } from "next";
import "../app/styles/styles.css"
import Header from "./components/layout/Header/Header";
import { Jost } from 'next/font/google'
import Footer from "./components/layout/Footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jost = Jost({
  adjustFontFallback:true
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`app ${jost.className}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
