
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {
  return (
    <html lang="it">
      <body >
       
        <main>
          TEST ADMIN
            {children}
          
        </main>
       
      </body>
    </html>
  );
}
